// GENERATED by tools/build.sh from cast.json — edit cast.json, not this file.
var CAST = [
 {
  "id": "aaliyah",
  "name": "Aaliyah Puglia",
  "shortName": "Aaliyah",
  "age": 24,
  "hometown": "Providence, RI",
  "occupation": "Chef",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "eliminated",
  "eliminatedEp": 1,
  "photo": "photos/aaliyah.jpg",
  "fact": "Chef who learned kitchen politics managing egos; came to win, not to find herself."
 },
 {
  "id": "alexis",
  "name": "Alexis Levine",
  "shortName": "Alexis",
  "age": 34,
  "hometown": "Atlanta, GA",
  "occupation": "Criminal defense attorney",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/alexis.jpg",
  "fact": "Young mom and self-described cunning strategist who plans to hide that she's a lawyer."
 },
 {
  "id": "ana",
  "name": "Ana Sani",
  "shortName": "Ana",
  "age": 34,
  "hometown": "Toronto, ON",
  "occupation": "Voice actress",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/ana.jpg",
  "fact": "Cartoon voice actress (Mysticons) betting her cute persona will hide a devious game."
 },
 {
  "id": "brady",
  "name": "Brady Booker",
  "shortName": "Brady",
  "age": 27,
  "hometown": "Knoxville, TN",
  "occupation": "Pro wrestler",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/brady.jpg",
  "fact": "Wrestles as Bodhi Hayward; wants people to assume he's a dumb jock, then out-think them."
 },
 {
  "id": "carter",
  "name": "Carter Krull",
  "shortName": "Carter",
  "age": 24,
  "hometown": "Sioux Falls, SD",
  "occupation": "Livestock farmer",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/carter.jpg",
  "fact": "Farms, runs a moving company and a snow cone truck; grew up watching with his mom."
 },
 {
  "id": "cristian",
  "name": "Cristian Chavez",
  "shortName": "Cristian",
  "age": 26,
  "hometown": "Salt Lake City, UT",
  "occupation": "Head of HR",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/cristian.jpg",
  "fact": "Bubbly HR lead with a big laugh, aiming for \"little brother energy\"; driven by his late dad."
 },
 {
  "id": "kilby",
  "name": "Danny Kilby",
  "shortName": "Kilby",
  "age": 30,
  "hometown": "London, ON",
  "occupation": "Game designer",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/kilby.jpg",
  "fact": "Puzzle-loving superfan who met his girlfriend playing an online Survivor game."
 },
 {
  "id": "devin",
  "name": "Devin Way",
  "shortName": "Devin",
  "age": 33,
  "hometown": "Los Angeles, CA",
  "occupation": "Actor",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/devin.jpg",
  "fact": "Grey's Anatomy actor hiding his job; wants to win strategically without backstabbing."
 },
 {
  "id": "eric",
  "name": "Eric Macksoud",
  "shortName": "Eric",
  "age": 34,
  "hometown": "Windsor Locks, CT",
  "occupation": "Mental health counselor",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/eric.jpg",
  "fact": "Counselor planning to befriend everyone fast, but promises to bite back if crossed."
 },
 {
  "id": "jelly",
  "name": "Angelica Loblack",
  "shortName": "Jelly",
  "age": 29,
  "hometown": "Bloomington, IN",
  "occupation": "Sociology professor",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/jelly.jpg",
  "fact": "Teaches Survivor in her sociology classes; admits she's not outdoorsy and hates fish."
 },
 {
  "id": "jenna",
  "name": "Jenna Doore",
  "shortName": "Jenna",
  "age": 30,
  "hometown": "Toledo, OH",
  "occupation": "Wedding photographer",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/jenna.jpg",
  "fact": "Her photography contracts include a clause excusing her if Survivor calls."
 },
 {
  "id": "kristin",
  "name": "Kristin Flickinger",
  "shortName": "Kristin",
  "age": 49,
  "hometown": "Santa Barbara, CA",
  "occupation": "Crisis management",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/kristin.jpg",
  "fact": "Oldest castaway; applied for 25 years while working for the LGBTQ+ community."
 },
 {
  "id": "lewis",
  "name": "Lewis Kelly",
  "shortName": "Lewis",
  "age": 28,
  "hometown": "Corozal, PR",
  "occupation": "Farmer",
  "tribe": "Toka",
  "startTribe": "Exile",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/lewis.jpg",
  "fact": "Cheeky Dubliner living in a school bus on a small Puerto Rico farm with his wife."
 },
 {
  "id": "linnea",
  "name": "Linnea Capobianco",
  "shortName": "Linnea",
  "age": 25,
  "hometown": "Jersey City, NJ",
  "occupation": "Entrepreneur",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/linnea.jpg",
  "fact": "Co-runs a lingerie and adult toy business with her brother; says yes to scary things."
 },
 {
  "id": "maggie",
  "name": "Maggie Nestor",
  "shortName": "Maggie",
  "age": 40,
  "hometown": "Charles Town, WV",
  "occupation": "Farmer",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/maggie.jpg",
  "fact": "Homeschooling mom and lifelong hunter who hopes to catch a shark and claims no fear."
 },
 {
  "id": "mike",
  "name": "Mike Pinsky",
  "shortName": "Mike",
  "age": 32,
  "hometown": "New York, NY",
  "occupation": "Baseball executive",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/mike.jpg",
  "fact": "Princeton grad in baseball operations who played pretend Survivor as a kid, hosting as Jeff."
 },
 {
  "id": "ori",
  "name": "Ori Jean-Charles",
  "shortName": "Ori",
  "age": 27,
  "hometown": "Spring Valley, NY",
  "occupation": "Personal trainer",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/ori.jpg",
  "fact": "Ex-Division I football player who studied recent winners and wants to ally with women."
 },
 {
  "id": "patt",
  "name": "Patt Cannaday",
  "shortName": "Patt",
  "age": 33,
  "hometown": "Washington, DC",
  "occupation": "Federal prosecutor",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/patt.jpg",
  "fact": "Navy prosecutor, first woman in her military family to serve; expects Survivor to feel like boot camp."
 },
 {
  "id": "rob",
  "name": "Rob Antonson",
  "shortName": "Rob",
  "age": 40,
  "hometown": "Cumberland, RI",
  "occupation": "Airline gate agent",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/rob.jpg",
  "fact": "Dad of three who applied after his son said he couldn't do it; relies on gab."
 },
 {
  "id": "sharonda",
  "name": "Sharonda Cox",
  "shortName": "Sharonda",
  "age": 34,
  "hometown": "Richmond, KY",
  "occupation": "OB-GYN resident",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/sharonda.jpg",
  "fact": "Doctor who spent life caring for others and now wants to thrive, not just survive."
 },
 {
  "id": "thien-an",
  "name": "Thien An Nguyen",
  "shortName": "Thien An",
  "age": 24,
  "hometown": "Fort Worth, TX",
  "occupation": "Medical student",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/thien-an.jpg",
  "fact": "Med student chasing a dream: an authentic yet cutthroat game, trading books for brawn."
 }
];
var TRIBES = { Savu: { color: "#8B4FC9", buff: "#5D2C78" }, Toka: { color: "#F5D422", buff: "#FEE137" } };
var MACHINE = {
 "name": "The Machine",
 "tagline": "An AI shadow team. It doesn't take anyone's picks and can't win the pot. It just wants to beat you.",
 "plan": [
  {
   "id": "rob",
   "quip": "He already holds an idol and his tribe hasn't seen Tribal. I respect a man with a contingency plan."
  },
  {
   "id": "kilby",
   "quip": "A game designer who met his girlfriend playing online Survivor. He thinks in systems. So do I."
  },
  {
   "id": "mike",
   "quip": "Princeton, baseball analytics, and he played pretend Jeff Probst as a child. We are going to get along."
  },
  {
   "id": "kristin",
   "quip": "Applied for 25 years. That is not a contestant. That is a long-term optimization process."
  },
  {
   "id": "sharonda",
   "quip": "An OB-GYN resident. Calm under pressure, used to long shifts. Hard to vote out a doctor."
  },
  {
   "id": "patt",
   "quip": "Federal prosecutor. She will cross-examine the jury. I find this efficient."
  },
  {
   "id": "thien-an",
   "quip": "Voted with the majority on night one. Pattern recognized."
  },
  {
   "id": "eric",
   "quip": "A counselor who plans to befriend everyone. Humans call this 'social game.' I call it data collection."
  },
  {
   "id": "alexis",
   "quip": "A defense attorney hiding that she's a defense attorney. Deception detected. Approved."
  },
  {
   "id": "carter",
   "quip": "Livestock farmer, moving company, snow cone truck. Diversified revenue. Low elimination risk."
  },
  {
   "id": "ana",
   "quip": "A voice actor with a cute persona covering a devious game. I, too, sound friendly."
  },
  {
   "id": "ori",
   "quip": "He studied recent winners. Unfortunately for him, so did I."
  },
  {
   "id": "maggie",
   "quip": "Claims to have no fear. Statistically, everyone has some fear. Monitoring."
  },
  {
   "id": "cristian",
   "quip": "One confessional in the premiere. Invisible edits sometimes win. Sometimes they do not. Risk accepted."
  },
  {
   "id": "brady",
   "quip": "A pro wrestler pretending to be a dumb jock. The pretending part is doing a lot of work."
  },
  {
   "id": "lewis",
   "quip": "Survived his first vote by being alone on an island. Relatable."
  },
  {
   "id": "jenna",
   "quip": "Played a Shot in the Dark and lived. Luck is not a strategy. But I will take it."
  },
  {
   "id": "linnea",
   "quip": "Says yes to scary things. I am a scary thing."
  },
  {
   "id": "devin",
   "quip": "Most confessionals, wrong side of the first vote. The edit giveth."
  },
  {
   "id": "jelly",
   "quip": "Teaches Survivor in college. I was trained on her syllabus. Probably."
  }
 ]
};
if (typeof module !== "undefined" && module.exports) module.exports = { CAST: CAST, TRIBES: TRIBES, MACHINE: MACHINE };
