// GENERATED by tools/build.sh — do not edit. Paste this whole file into the Apps Script editor.
// Built 2026-09-28 22:12
// GENERATED by tools/build.sh from cast.json — edit cast.json, not this file.
var CAST = [
 {
  "id": "aaliyah",
  "name": "Aaliyah Puglia",
  "shortName": "Aaliyah",
  "age": 24,
  "hometown": "Providence, RI",
  "occupation": "Chef",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "eliminated",
  "eliminatedEp": 1,
  "photo": "photos/aaliyah.jpg",
  "fact": "Chef who learned kitchen politics managing egos; came to win, not to find herself."
 },
 {
  "id": "alexis",
  "name": "Alexis Levine",
  "shortName": "Alexis",
  "age": 34,
  "hometown": "Atlanta, GA",
  "occupation": "Criminal defense attorney",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/alexis.jpg",
  "fact": "Young mom and self-described cunning strategist who plans to hide that she's a lawyer."
 },
 {
  "id": "ana",
  "name": "Ana Sani",
  "shortName": "Ana",
  "age": 34,
  "hometown": "Toronto, ON",
  "occupation": "Voice actress",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/ana.jpg",
  "fact": "Cartoon voice actress (Mysticons) betting her cute persona will hide a devious game."
 },
 {
  "id": "brady",
  "name": "Brady Booker",
  "shortName": "Brady",
  "age": 27,
  "hometown": "Knoxville, TN",
  "occupation": "Pro wrestler",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/brady.jpg",
  "fact": "Wrestles as Bodhi Hayward; wants people to assume he's a dumb jock, then out-think them."
 },
 {
  "id": "carter",
  "name": "Carter Krull",
  "shortName": "Carter",
  "age": 24,
  "hometown": "Sioux Falls, SD",
  "occupation": "Livestock farmer",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/carter.jpg",
  "fact": "Farms, runs a moving company and a snow cone truck; grew up watching with his mom."
 },
 {
  "id": "cristian",
  "name": "Cristian Chavez",
  "shortName": "Cristian",
  "age": 26,
  "hometown": "Salt Lake City, UT",
  "occupation": "Head of HR",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/cristian.jpg",
  "fact": "Bubbly HR lead with a big laugh, aiming for \"little brother energy\"; driven by his late dad."
 },
 {
  "id": "kilby",
  "name": "Danny Kilby",
  "shortName": "Kilby",
  "age": 30,
  "hometown": "London, ON",
  "occupation": "Game designer",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/kilby.jpg",
  "fact": "Puzzle-loving superfan who met his girlfriend playing an online Survivor game."
 },
 {
  "id": "devin",
  "name": "Devin Way",
  "shortName": "Devin",
  "age": 33,
  "hometown": "Los Angeles, CA",
  "occupation": "Actor",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/devin.jpg",
  "fact": "Grey's Anatomy actor hiding his job; wants to win strategically without backstabbing."
 },
 {
  "id": "eric",
  "name": "Eric Macksoud",
  "shortName": "Eric",
  "age": 34,
  "hometown": "Windsor Locks, CT",
  "occupation": "Mental health counselor",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/eric.jpg",
  "fact": "Counselor planning to befriend everyone fast, but promises to bite back if crossed."
 },
 {
  "id": "jelly",
  "name": "Angelica Loblack",
  "shortName": "Jelly",
  "age": 29,
  "hometown": "Bloomington, IN",
  "occupation": "Sociology professor",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/jelly.jpg",
  "fact": "Teaches Survivor in her sociology classes; admits she's not outdoorsy and hates fish."
 },
 {
  "id": "jenna",
  "name": "Jenna Doore",
  "shortName": "Jenna",
  "age": 30,
  "hometown": "Toledo, OH",
  "occupation": "Wedding photographer",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/jenna.jpg",
  "fact": "Her photography contracts include a clause excusing her if Survivor calls."
 },
 {
  "id": "kristin",
  "name": "Kristin Flickinger",
  "shortName": "Kristin",
  "age": 49,
  "hometown": "Santa Barbara, CA",
  "occupation": "Crisis management",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/kristin.jpg",
  "fact": "Oldest castaway; applied for 25 years while working for the LGBTQ+ community."
 },
 {
  "id": "lewis",
  "name": "Lewis Kelly",
  "shortName": "Lewis",
  "age": 28,
  "hometown": "Corozal, PR",
  "occupation": "Farmer",
  "tribe": "Toka",
  "startTribe": "Exile",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/lewis.jpg",
  "fact": "Cheeky Dubliner living in a school bus on a small Puerto Rico farm with his wife."
 },
 {
  "id": "linnea",
  "name": "Linnea Capobianco",
  "shortName": "Linnea",
  "age": 25,
  "hometown": "Jersey City, NJ",
  "occupation": "Entrepreneur",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/linnea.jpg",
  "fact": "Co-runs a lingerie and adult toy business with her brother; says yes to scary things."
 },
 {
  "id": "maggie",
  "name": "Maggie Nestor",
  "shortName": "Maggie",
  "age": 40,
  "hometown": "Charles Town, WV",
  "occupation": "Farmer",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/maggie.jpg",
  "fact": "Homeschooling mom and lifelong hunter who hopes to catch a shark and claims no fear."
 },
 {
  "id": "mike",
  "name": "Mike Pinsky",
  "shortName": "Mike",
  "age": 32,
  "hometown": "New York, NY",
  "occupation": "Baseball executive",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/mike.jpg",
  "fact": "Princeton grad in baseball operations who played pretend Survivor as a kid, hosting as Jeff."
 },
 {
  "id": "ori",
  "name": "Ori Jean-Charles",
  "shortName": "Ori",
  "age": 27,
  "hometown": "Spring Valley, NY",
  "occupation": "Personal trainer",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/ori.jpg",
  "fact": "Ex-Division I football player who studied recent winners and wants to ally with women."
 },
 {
  "id": "patt",
  "name": "Patt Cannaday",
  "shortName": "Patt",
  "age": 33,
  "hometown": "Washington, DC",
  "occupation": "Federal prosecutor",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/patt.jpg",
  "fact": "Navy prosecutor, first woman in her military family to serve; expects Survivor to feel like boot camp."
 },
 {
  "id": "rob",
  "name": "Rob Antonson",
  "shortName": "Rob",
  "age": 40,
  "hometown": "Cumberland, RI",
  "occupation": "Airline gate agent",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/rob.jpg",
  "fact": "Dad of three who applied after his son said he couldn't do it; relies on gab."
 },
 {
  "id": "sharonda",
  "name": "Sharonda Cox",
  "shortName": "Sharonda",
  "age": 34,
  "hometown": "Richmond, KY",
  "occupation": "OB-GYN resident",
  "tribe": "Savu",
  "startTribe": "Savu",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/sharonda.jpg",
  "fact": "Doctor who spent life caring for others and now wants to thrive, not just survive."
 },
 {
  "id": "thien-an",
  "name": "Thien An Nguyen",
  "shortName": "Thien An",
  "age": 24,
  "hometown": "Fort Worth, TX",
  "occupation": "Medical student",
  "tribe": "Toka",
  "startTribe": "Toka",
  "status": "active",
  "eliminatedEp": null,
  "photo": "photos/thien-an.jpg",
  "fact": "Med student chasing a dream: an authentic yet cutthroat game, trading books for brawn."
 }
];
var TRIBES = { Savu: { color: "#8B4FC9", buff: "#5D2C78" }, Toka: { color: "#F5D422", buff: "#FEE137" } };
// =============================================================
// SURVIVOR 51 FANTASY — shared game engine
// -------------------------------------------------------------
// Pure functions only: no DOM, no Google APIs, no clocks read directly.
// The same file runs in three places:
//   1. the website (index.html loads it as a <script>)
//   2. the Google Apps Script backend (tools/build-gs.sh prepends it to Code.gs)
//   3. node tests and the local mock server
// So the draft rules and the scoring can never drift between client and server.
// =============================================================

var Engine = (function () {
  'use strict';

  // ---------- Scoring (identical to Season 50) ----------
  var SCORING = [
    { key: 'survives',      label: 'Survives Tribal',            short: 'Survived',   points: 3,   type: 'check' },
    { key: 'findIdol',      label: 'Finds / possesses idol',     short: 'Idol found', points: 3,   type: 'check' },
    { key: 'playIdol',      label: 'Plays idol successfully',    short: 'Idol play',  points: 8,   type: 'check' },
    { key: 'findAdvantage', label: 'Finds / wins advantage',     short: 'Adv found',  points: 3,   type: 'check' },
    { key: 'playAdvantage', label: 'Plays advantage to effect',  short: 'Adv play',   points: 4,   type: 'check' },
    { key: 'makesMerge',    label: 'Makes the merge',            short: 'Merge',      points: 4,   type: 'check' },
    { key: 'idolPocket',    label: 'Goes home with idol',        short: 'Idol pocket',points: -5,  type: 'check' },
    { key: 'quit',          label: 'Quits (non-medical)',        short: 'Quit',       points: -15, type: 'check' },
    { key: 'immunityWin',   label: 'Individual immunity win',    short: 'Immunity',   points: 5,   type: 'check' },
    { key: 'firemaking',    label: 'Wins fire-making',           short: 'Fire',       points: 5,   type: 'check' },
    { key: 'juryVotes',     label: 'Jury votes (runner-up)',     short: 'Jury votes', points: 3,   type: 'number' },
    { key: 'soleSurvivor',  label: 'Sole Survivor',              short: 'Winner',     points: 20,  type: 'check' },
    { key: 'iconic',        label: 'Most Iconic (league vote)',  short: 'Iconic',     points: 7,   type: 'check' }
  ];

  var DEFAULT_SETTINGS = {
    rounds: 4,              // Season 50 ran 4 rounds with 9 players
    maxPerCastaway: 2,      // a castaway comes off the board after 2 picks
    clockSec: 90,           // pick clock
    scoringStartEp: 3,      // Episode 2 does not count (draft happens during/around it)
    mergeMaxPerCastaway: 2,
    winnerBetPoints: 10,    // Pick the Winner bet, locks when the draft completes
    lastEpisode: 13
  };

  var PLAYER_COLORS = [
    '#FF7A2F', '#2EC4B6', '#F2C14E', '#E0569B', '#7B8CFF', '#8BD346',
    '#FF5A5F', '#3FA9F5', '#C38BFF', '#F29E4C', '#5ED9A0', '#E8E8E8'
  ];

  // ---------- Errors ----------
  function fail(code, extra) {
    var e = new Error(code);
    e.code = code;
    if (extra) e.extra = extra;
    throw e;
  }

  // ---------- League skeleton ----------
  function newLeague(season) {
    return {
      season: season || 51,
      version: 0,
      settings: clone(DEFAULT_SETTINGS),
      players: [],
      castaways: {},     // overrides: { slug: { status, eliminatedEp, elimType, tribe } }
      draft: newDraft('main'),
      merge: newDraft('merge'),
      winnerBets: null,  // revealed copy, filled when the draft completes
      currentEp: 2,
      updatedAt: 0
    };
  }

  function newDraft(kind) {
    return {
      kind: kind,
      status: kind === 'main' ? 'open' : 'off', // open | live | paused | complete | off
      order: [],
      rounds: kind === 'main' ? DEFAULT_SETTINGS.rounds : 1,
      snake: kind === 'main',
      clockSec: DEFAULT_SETTINGS.clockSec,
      picks: [],
      deadline: null,
      pausedRemainingMs: null,
      startedAt: null,
      completedAt: null,
      startEp: null        // merge only: first episode the merge pick scores
    };
  }

  function clone(o) { return JSON.parse(JSON.stringify(o)); }

  // ---------- Cast helpers ----------
  // cast = static array from cast.js: [{ id, name, shortName, tribe, status, eliminatedEp }]
  function castawayStatus(league, cast, id) {
    var base = null;
    for (var i = 0; i < cast.length; i++) if (cast[i].id === id) { base = cast[i]; break; }
    if (!base) return null;
    var o = (league.castaways && league.castaways[id]) || {};
    return {
      id: id,
      status: o.status || base.status || 'active',
      eliminatedEp: o.eliminatedEp != null ? o.eliminatedEp : (base.eliminatedEp != null ? base.eliminatedEp : null),
      elimType: o.elimType || base.elimType || null,
      tribe: o.tribe || base.tribe
    };
  }

  function activeCastawayIds(league, cast) {
    return cast.filter(function (c) { return castawayStatus(league, cast, c.id).status === 'active'; })
               .map(function (c) { return c.id; });
  }

  function activePlayers(league) {
    return league.players.filter(function (p) { return !p.removed; });
  }

  function playerById(league, id) {
    for (var i = 0; i < league.players.length; i++) if (league.players[i].id === id) return league.players[i];
    return null;
  }

  // ---------- Draft order ----------
  function totalSlots(draft) { return draft.order.length * draft.rounds; }

  function slotInfo(draft, n) {
    var N = draft.order.length;
    if (!N || n >= totalSlots(draft)) return null;
    var round = Math.floor(n / N);
    var pos = n % N;
    var reversed = draft.snake && round % 2 === 1;
    return { n: n, round: round + 1, pickInRound: pos + 1, playerId: draft.order[reversed ? N - 1 - pos : pos] };
  }

  function currentSlot(draft) {
    if (draft.status !== 'live' && draft.status !== 'paused') return null;
    return slotInfo(draft, draft.picks.length);
  }

  // Upcoming slots (including current), for the "on deck" ticker.
  function upcomingSlots(draft, count) {
    var out = [];
    for (var n = draft.picks.length; n < totalSlots(draft) && out.length < count; n++) out.push(slotInfo(draft, n));
    return out;
  }

  function shuffle(arr, rand) {
    var a = arr.slice();
    rand = rand || Math.random;
    for (var i = a.length - 1; i > 0; i--) {
      var j = Math.floor(rand() * (i + 1));
      var t = a[i]; a[i] = a[j]; a[j] = t;
    }
    return a;
  }

  // ---------- Rosters ----------
  function picksBy(draft, playerId) {
    return draft.picks.filter(function (p) { return p.playerId === playerId && p.castawayId; })
                      .map(function (p) { return p.castawayId; });
  }

  function timesPicked(draft, castawayId) {
    var n = 0;
    draft.picks.forEach(function (p) { if (p.castawayId === castawayId) n++; });
    return n;
  }

  function roster(league, playerId) {
    return {
      draft: picksBy(league.draft, playerId),
      merge: picksBy(league.merge, playerId)
    };
  }

  // Why a castaway can't be picked right now (null = legal).
  // If every castaway is blocked by the two-pick cap (can happen on the very last picks
  // of a completely full board), the cap is lifted for that one pick instead of skipping.
  function pickBlocker(league, cast, kind, playerId, castawayId) {
    var b = strictBlocker(league, cast, kind, playerId, castawayId);
    if (b !== 'off_board') return b;
    for (var i = 0; i < cast.length; i++) {
      if (!strictBlocker(league, cast, kind, playerId, cast[i].id)) return 'off_board';
    }
    return null;
  }

  function strictBlocker(league, cast, kind, playerId, castawayId) {
    var draft = kind === 'merge' ? league.merge : league.draft;
    var st = castawayStatus(league, cast, castawayId);
    if (!st) return 'unknown_castaway';
    if (st.status !== 'active') return 'castaway_out';
    var cap = kind === 'merge' ? league.settings.mergeMaxPerCastaway : league.settings.maxPerCastaway;
    if (timesPicked(draft, castawayId) >= cap) return 'off_board';
    if (picksBy(league.draft, playerId).indexOf(castawayId) !== -1) return 'already_yours';
    if (kind === 'merge' && picksBy(league.merge, playerId).indexOf(castawayId) !== -1) return 'already_yours';
    return null;
  }

  function legalPicks(league, cast, kind, playerId) {
    return cast.map(function (c) { return c.id; })
               .filter(function (id) { return !pickBlocker(league, cast, kind, playerId, id); });
  }

  // League-wide "consensus" ranking from everyone's queues (average rank; unranked = last).
  // Used as the fallback when a player's own queue is empty or exhausted.
  function consensusRanking(cast, queues) {
    var ids = cast.map(function (c) { return c.id; });
    var score = {};
    ids.forEach(function (id) { score[id] = 0; });
    var qs = Object.keys(queues || {}).map(function (k) { return queues[k] || []; })
                   .filter(function (q) { return q.length; });
    ids.forEach(function (id) {
      qs.forEach(function (q) {
        var r = q.indexOf(id);
        score[id] += r === -1 ? ids.length : r;
      });
    });
    return ids.slice().sort(function (a, b) {
      return (score[a] - score[b]) || (ids.indexOf(a) - ids.indexOf(b));
    });
  }

  function chooseAutoPick(league, cast, kind, playerId, queue, consensus) {
    var legal = legalPicks(league, cast, kind, playerId);
    if (!legal.length) return null;
    var lists = [queue || [], consensus || []];
    for (var l = 0; l < lists.length; l++) {
      for (var i = 0; i < lists[l].length; i++) {
        if (legal.indexOf(lists[l][i]) !== -1) return { castawayId: lists[l][i], source: l === 0 ? 'queue' : 'consensus' };
      }
    }
    return { castawayId: legal[0], source: 'first' };
  }

  // ---------- Draft lifecycle ----------
  function startDraft(league, cast, opts) {
    var d = league.draft;
    if (d.status !== 'open') fail('draft_already_started');
    var players = activePlayers(league);
    if (players.length < 2) fail('need_two_players');
    var rounds = opts.rounds || league.settings.rounds;
    var capacity = activeCastawayIds(league, cast).length * league.settings.maxPerCastaway;
    if (players.length * rounds > capacity) fail('too_many_picks', { capacity: capacity, needed: players.length * rounds });
    var order = opts.order || shuffle(players.map(function (p) { return p.id; }), opts.rand);
    d.order = order;
    d.rounds = rounds;
    d.clockSec = opts.clockSec || league.settings.clockSec;
    d.status = 'live';
    d.startedAt = opts.now;
    d.picks = [];
    // First pick gets a little extra time for the order reveal.
    d.deadline = opts.now + (d.clockSec + (opts.revealSec || 0)) * 1000;
    d.pausedRemainingMs = null;
    league.settings.rounds = rounds;
    return d;
  }

  function startMerge(league, cast, opts) {
    var m = league.merge;
    if (m.status !== 'off' && m.status !== 'complete') fail('merge_already_started');
    if (league.draft.status !== 'complete') fail('main_draft_not_complete');
    if (!opts.order || !opts.order.length) fail('missing_order');
    m.order = opts.order;
    m.rounds = 1;
    m.snake = false;
    m.clockSec = opts.clockSec || 0;           // 0 = no clock (merge draft runs async over a few days)
    m.status = 'live';
    m.picks = [];
    m.startedAt = opts.now;
    m.startEp = opts.startEp;
    m.deadline = m.clockSec ? opts.now + m.clockSec * 1000 : null;
    m.pausedRemainingMs = null;
    return m;
  }

  // Apply a pick. `expectedN` guards against double-submits and stale screens.
  function applyPick(league, cast, kind, playerId, castawayId, opts) {
    var draft = kind === 'merge' ? league.merge : league.draft;
    if (draft.status === 'paused' && !opts.admin) fail('draft_paused');
    if (draft.status !== 'live' && draft.status !== 'paused') fail('draft_not_live');
    var slot = currentSlot(draft);
    if (!slot) fail('draft_complete');
    if (opts.expectedN != null && opts.expectedN !== slot.n) fail('stale_pick', { current: slot.n });
    if (slot.playerId !== playerId) fail('not_your_turn', { current: slot.playerId });
    var blocker = pickBlocker(league, cast, kind, playerId, castawayId);
    if (blocker) fail(blocker);
    draft.picks.push({ n: slot.n, playerId: playerId, castawayId: castawayId, auto: opts.auto || null, at: opts.now });
    afterPick(league, draft, opts.now);
    return slot;
  }

  function skipSlot(league, draft, now, reason) {
    var slot = currentSlot(draft);
    draft.picks.push({ n: slot.n, playerId: slot.playerId, castawayId: null, auto: reason || 'skipped', at: now });
    afterPick(league, draft, now);
  }

  function afterPick(league, draft, now) {
    if (draft.picks.length >= totalSlots(draft)) {
      draft.status = 'complete';
      draft.deadline = null;
      draft.completedAt = now;
      return;
    }
    if (draft.status === 'paused') {
      draft.pausedRemainingMs = draft.clockSec * 1000;
    } else {
      draft.deadline = draft.clockSec ? now + draft.clockSec * 1000 : null;
    }
  }

  // Called on every server read. If the clock has run out, auto-pick for whoever is up.
  // Only one auto-pick per tick, and the next player always gets a full clock from `now`,
  // so a room-wide wifi drop can't cascade into everyone being auto-drafted.
  function tick(league, cast, kind, now, queues) {
    var draft = kind === 'merge' ? league.merge : league.draft;
    if (draft.status !== 'live' || !draft.deadline || now < draft.deadline) return null;
    var slot = currentSlot(draft);
    if (!slot) return null;
    var choice = chooseAutoPick(league, cast, kind, slot.playerId, (queues || {})[slot.playerId], consensusRanking(cast, queues));
    if (!choice) { skipSlot(league, draft, now, 'no_legal_pick'); return { slot: slot, castawayId: null }; }
    applyPick(league, cast, kind, slot.playerId, choice.castawayId, { now: now, auto: choice.source });
    return { slot: slot, castawayId: choice.castawayId, source: choice.source };
  }

  function pause(draft, now) {
    if (draft.status !== 'live') fail('not_live');
    draft.status = 'paused';
    draft.pausedRemainingMs = draft.deadline ? Math.max(0, draft.deadline - now) : null;
    draft.deadline = null;
  }

  function resume(draft, now) {
    if (draft.status !== 'paused') fail('not_paused');
    draft.status = 'live';
    var ms = draft.pausedRemainingMs;
    if (draft.clockSec) draft.deadline = now + Math.max(ms == null ? draft.clockSec * 1000 : ms, 15000);
    draft.pausedRemainingMs = null;
  }

  function undo(draft, now) {
    if (!draft.picks.length) fail('nothing_to_undo');
    var last = draft.picks.pop();
    if (draft.status === 'complete') { draft.status = 'paused'; draft.completedAt = null; }
    if (draft.status === 'paused') { draft.pausedRemainingMs = draft.clockSec * 1000; draft.deadline = null; }
    else draft.deadline = draft.clockSec ? now + draft.clockSec * 1000 : null;
    return last;
  }

  // ---------- Scoring ----------
  // episodes: { "3": { scores: { slug: { survives: true, ... } }, ... }, ... }
  function castawayEpisodePoints(episodes, id, ep) {
    var e = episodes && episodes[ep];
    var s = e && e.scores && e.scores[id];
    if (!s) return 0;
    var t = 0;
    SCORING.forEach(function (cat) {
      if (cat.type === 'check' && s[cat.key]) t += cat.points;
      if (cat.type === 'number' && s[cat.key]) t += Number(s[cat.key]) * cat.points;
    });
    return t;
  }

  function episodeNumbers(league, episodes) {
    var start = league.settings.scoringStartEp;
    return Object.keys(episodes || {}).map(Number)
      .filter(function (n) { return n >= start && episodes[n] && episodes[n].published !== false; })
      .sort(function (a, b) { return a - b; });
  }

  function castawayTotal(league, episodes, id, fromEp) {
    var t = 0;
    episodeNumbers(league, episodes).forEach(function (ep) {
      if (fromEp == null || ep >= fromEp) t += castawayEpisodePoints(episodes, id, ep);
    });
    return t;
  }

  function soleSurvivorId(episodes) {
    var found = null;
    Object.keys(episodes || {}).forEach(function (ep) {
      var sc = episodes[ep].scores || {};
      Object.keys(sc).forEach(function (id) { if (sc[id].soleSurvivor) found = id; });
    });
    return found;
  }

  // Points a player earns in one episode (draft picks + merge pick from merge.startEp onward).
  function playerEpisodePoints(league, episodes, playerId, ep) {
    if (ep < league.settings.scoringStartEp) return 0;
    var r = roster(league, playerId);
    var t = 0;
    r.draft.forEach(function (id) { t += castawayEpisodePoints(episodes, id, ep); });
    if (league.merge.startEp != null && ep >= league.merge.startEp) {
      r.merge.forEach(function (id) {
        if (r.draft.indexOf(id) === -1) t += castawayEpisodePoints(episodes, id, ep);
      });
    }
    return t;
  }

  function winnerBetBonus(league, episodes, playerId) {
    var bets = league.winnerBets || {};
    var winner = soleSurvivorId(episodes);
    return winner && bets[playerId] === winner ? league.settings.winnerBetPoints : 0;
  }

  function playerTotal(league, episodes, playerId) {
    var t = 0;
    episodeNumbers(league, episodes).forEach(function (ep) { t += playerEpisodePoints(league, episodes, playerId, ep); });
    return t + winnerBetBonus(league, episodes, playerId);
  }

  // Standings with shared ranks for ties, plus last-episode delta and rank movement.
  function standings(league, episodes) {
    var eps = episodeNumbers(league, episodes);
    var last = eps[eps.length - 1];
    var rows = activePlayers(league).map(function (p) {
      var total = playerTotal(league, episodes, p.id);
      var lastPts = last != null ? playerEpisodePoints(league, episodes, p.id, last) : 0;
      return { playerId: p.id, name: p.name, color: p.color, total: total, lastEp: lastPts, prevTotal: total - lastPts };
    });
    rankRows(rows, 'total', 'rank');
    rankRows(rows, 'prevTotal', 'prevRank');
    rows.forEach(function (r) { r.move = eps.length > 1 ? r.prevRank - r.rank : 0; });
    return rows.sort(function (a, b) { return (b.total - a.total) || a.name.localeCompare(b.name); });
  }

  function rankRows(rows, key, out) {
    var sorted = rows.slice().sort(function (a, b) { return b[key] - a[key]; });
    sorted.forEach(function (r, i) {
      r[out] = i > 0 && sorted[i - 1][key] === r[key] ? sorted[i - 1][out] : i + 1;
    });
  }

  // Cumulative totals per episode, for the season race chart.
  function raceSeries(league, episodes) {
    var eps = episodeNumbers(league, episodes);
    return activePlayers(league).map(function (p) {
      var run = 0;
      return { playerId: p.id, name: p.name, color: p.color, points: eps.map(function (ep) {
        run += playerEpisodePoints(league, episodes, p.id, ep);
        return { ep: ep, total: run };
      }) };
    });
  }

  // ---------- Win probability (Monte Carlo) ----------
  // Simulates the rest of the season: random boot order among active castaways, with
  // survival, merge, immunity, fire, jury and winner points assigned the way the rules do.
  // Deliberately simple and unbiased — it doesn't know who's "good", only who's still alive.
  function winProbabilities(league, cast, episodes, opts) {
    opts = opts || {};
    var sims = opts.sims || 3000;
    var rand = opts.rand || Math.random;
    var players = activePlayers(league);
    if (!players.length) return {};
    var active = activeCastawayIds(league, cast);
    var base = {};
    players.forEach(function (p) { base[p.id] = playerTotal(league, episodes, p.id); });
    if (active.length <= 1) {
      var out1 = {}; var best = Math.max.apply(null, players.map(function (p) { return base[p.id]; }));
      var leaders = players.filter(function (p) { return base[p.id] === best; });
      players.forEach(function (p) { out1[p.id] = leaders.indexOf(p) !== -1 ? 1 / leaders.length : 0; });
      return out1;
    }
    var mergeAt = opts.mergeAt || 12;           // castaways left at the merge (typical new-era season)
    var merged = active.length <= mergeAt;
    var ownersDraft = {}; var ownersMerge = {};
    players.forEach(function (p) {
      var r = roster(league, p.id);
      r.draft.forEach(function (id) { (ownersDraft[id] = ownersDraft[id] || []).push(p.id); });
      r.merge.forEach(function (id) { if (r.draft.indexOf(id) === -1) (ownersMerge[id] = ownersMerge[id] || []).push(p.id); });
    });
    var bets = league.winnerBets || {};
    var wins = {}; players.forEach(function (p) { wins[p.id] = 0; });

    var tribeOf = {};
    active.forEach(function (id) { tribeOf[id] = castawayStatus(league, cast, id).tribe; });

    for (var s = 0; s < sims; s++) {
      var pts = {}; active.forEach(function (id) { pts[id] = 0; });
      var alive = shuffle(active, rand);        // boot order: alive[0] goes next
      var isMerged = merged;
      while (alive.length > 3) {
        if (!isMerged && alive.length <= mergeAt) { alive.forEach(function (id) { pts[id] += 4; }); isMerged = true; }
        if (isMerged) pts[alive[1 + Math.floor(rand() * (alive.length - 1))]] += 5;   // immunity (never the boot)
        var boot = alive.shift();
        // Only castaways who attend tribal earn "survives": pre-merge that's the boot's tribe.
        alive.forEach(function (id) { if (isMerged || tribeOf[id] === tribeOf[boot]) pts[id] += 3; });
        if (alive.length === 3 && isMerged) pts[alive[Math.floor(rand() * 3)]] += 5;  // fire-making at final 4
      }
      // Final three: random winner, runners-up split a few jury votes.
      var winner = alive[Math.floor(rand() * alive.length)];
      pts[winner] += 20;
      alive.forEach(function (id) { if (id !== winner) pts[id] += 3 * Math.floor(rand() * 3); });
      var best2 = -Infinity; var leaders2 = [];
      players.forEach(function (p) {
        var t = base[p.id];
        var r = roster(league, p.id);
        r.draft.forEach(function (id) { if (pts[id]) t += pts[id]; });
        r.merge.forEach(function (id) { if (r.draft.indexOf(id) === -1 && pts[id]) t += pts[id]; });
        if (bets[p.id] === winner) t += league.settings.winnerBetPoints;
        if (t > best2) { best2 = t; leaders2 = [p.id]; } else if (t === best2) leaders2.push(p.id);
      });
      leaders2.forEach(function (id) { wins[id] += 1 / leaders2.length; });
    }
    var out = {};
    players.forEach(function (p) { out[p.id] = wins[p.id] / sims; });
    return out;
  }

  // ---------- Public view ----------
  // Strips secrets. Winner bets stay hidden until the draft completes.
  function publicLeague(league) {
    var l = clone(league);
    if (league.draft.status !== 'complete') l.winnerBets = null;
    return l;
  }

  return {
    SCORING: SCORING,
    DEFAULT_SETTINGS: DEFAULT_SETTINGS,
    PLAYER_COLORS: PLAYER_COLORS,
    fail: fail,
    clone: clone,
    newLeague: newLeague,
    newDraft: newDraft,
    castawayStatus: castawayStatus,
    activeCastawayIds: activeCastawayIds,
    activePlayers: activePlayers,
    playerById: playerById,
    totalSlots: totalSlots,
    slotInfo: slotInfo,
    currentSlot: currentSlot,
    upcomingSlots: upcomingSlots,
    shuffle: shuffle,
    picksBy: picksBy,
    timesPicked: timesPicked,
    roster: roster,
    pickBlocker: pickBlocker,
    legalPicks: legalPicks,
    consensusRanking: consensusRanking,
    chooseAutoPick: chooseAutoPick,
    startDraft: startDraft,
    startMerge: startMerge,
    applyPick: applyPick,
    tick: tick,
    pause: pause,
    resume: resume,
    undo: undo,
    castawayEpisodePoints: castawayEpisodePoints,
    episodeNumbers: episodeNumbers,
    castawayTotal: castawayTotal,
    soleSurvivorId: soleSurvivorId,
    playerEpisodePoints: playerEpisodePoints,
    winnerBetBonus: winnerBetBonus,
    playerTotal: playerTotal,
    standings: standings,
    raceSeries: raceSeries,
    winProbabilities: winProbabilities,
    publicLeague: publicLeague
  };
})();

// =============================================================
// SURVIVOR 51 FANTASY — backend API (runs inside Google Apps Script)
// -------------------------------------------------------------
// Every write is an atomic "action" validated on the server, instead of Season 50's
// "whole state publish" (which is how stale tabs wiped the sheet mid-merge-draft).
// Storage and Google services sit behind `Platform` (platform.js) so the same file
// runs under the local node mock server (dev/mock-server.js) for testing.
//
// GET  ?action=state            → public league + episodes + notes (+ runs the pick clock)
// POST {action:'join'|'login'|'prefs'|'pick'|'admin', ...}
// =============================================================

var PRIVATE_KEY = 'private';
var LEAGUE_KEY = 'league';
// Picks sent in the last seconds still count: network lag means phones show a little more time than the server has.
var GRACE_MS = 3000;

function doGet(e) {
  try {
    var action = (e && e.parameter && e.parameter.action) || 'state';
    if (action === 'state') return Platform.raw(publicPayload());
    if (action === 'ping') return Platform.json({ ok: true, serverTime: Date.now() });
    return Platform.json({ ok: false, error: 'unknown_action' });
  } catch (err) {
    return Platform.json({ ok: false, error: err.code || err.message });
  }
}

function doPost(e) {
  var body;
  try { body = JSON.parse(e.postData.contents); } catch (x) { return Platform.json({ ok: false, error: 'bad_json' }); }
  try {
    var out;
    switch (body.action) {
      case 'join':  out = Platform.withLock(function () { return actJoin(body); }); break;
      case 'login': out = actLogin(body); break;
      case 'prefs': out = Platform.withLock(function () { return actPrefs(body); }); break;
      case 'pick':  out = Platform.withLock(function () { return actPick(body); }); break;
      case 'admin': out = Platform.withLock(function () { return actAdmin(body); }); break;
      default: Engine.fail('unknown_action');
    }
    out.ok = true;
    out.serverTime = Date.now();
    return Platform.json(out);
  } catch (err) {
    return Platform.json({ ok: false, error: err.code || err.message, extra: err.extra || null, serverTime: Date.now() });
  }
}

// ---------- Storage ----------
function loadAll() {
  var all = Platform.storeLoadAll();          // { key: parsedValue }
  if (!all[LEAGUE_KEY]) all[LEAGUE_KEY] = Engine.newLeague(51);
  if (!all[PRIVATE_KEY]) all[PRIVATE_KEY] = { byId: {} };
  return all;
}

function saveLeague(all, reason) {
  var league = all[LEAGUE_KEY];
  league.version = (league.version || 0) + 1;
  league.updatedAt = Date.now();
  Platform.storeSet(LEAGUE_KEY, league);
  Platform.cacheClear();
  Platform.backup(reason, league);
}

function savePrivate(all) {
  Platform.storeSet(PRIVATE_KEY, all[PRIVATE_KEY]);
}

function queuesOf(all) {
  var q = {};
  var byId = all[PRIVATE_KEY].byId;
  Object.keys(byId).forEach(function (id) { q[id] = byId[id].queue || []; });
  return q;
}

// ---------- Public read (cached) ----------
function publicPayload() {
  var cached = Platform.cacheGet();
  if (cached) {
    var meta = cached.meta;
    var now = Date.now();
    var due = (meta.main && now >= meta.main) || (meta.merge && now >= meta.merge) || (meta.start && now >= meta.start);
    if (!due) return withTime(cached.body);
  }
  // Cache miss or a pick clock has expired: rebuild from the sheet (under lock if we may write).
  return withTime(Platform.withLock(function () {
    // Another request may have rebuilt the cache while we waited for the lock.
    var again = Platform.cacheGet();
    if (again) {
      var m2 = again.meta, t2 = Date.now();
      if (!((m2.main && t2 >= m2.main) || (m2.merge && t2 >= m2.merge) || (m2.start && t2 >= m2.start))) return again.body;
    }
    var all = loadAll();
    var league = all[LEAGUE_KEY];
    var now = Date.now();
    var changed = false;
    // Scheduled start: the draft begins on its own at league.draftAt if autoStart is on.
    if (league.draft.status === 'open' && league.autoStart && league.draftAt && now >= Date.parse(league.draftAt)) {
      try {
        Engine.startDraft(league, CAST, { now: now, revealSec: 20, rounds: autoRounds(league) });
        changed = true;
      } catch (e) { league.autoStart = false; league.autoStartError = e.code || e.message; changed = true; }
    }
    ['main', 'merge'].forEach(function (kind) {
      var r = Engine.tick(league, CAST, kind, now - GRACE_MS, queuesOf(all));
      if (r) { changed = true; onDraftProgress(all, kind); }
    });
    if (changed) saveLeague(all, 'autopick');
    var body = buildPublicBody(all);
    Platform.cachePut(body, {
      main: league.draft.status === 'live' && league.draft.deadline ? league.draft.deadline + GRACE_MS : null,
      merge: league.merge.status === 'live' && league.merge.deadline ? league.merge.deadline + GRACE_MS : null,
      start: league.draft.status === 'open' && league.autoStart && league.draftAt ? Date.parse(league.draftAt) : null
    });
    return body;
  }));
}

// As many rounds as the board allows, up to the configured number.
function autoRounds(league) {
  var n = Engine.activePlayers(league).length || 1;
  var cap = Engine.activeCastawayIds(league, CAST).length * league.settings.maxPerCastaway;
  return Math.max(1, Math.min(league.settings.rounds, Math.floor(cap / n)));
}

function withTime(body) {
  return '{"ok":true,"serverTime":' + Date.now() + ',"data":' + body + '}';
}

function buildPublicBody(all) {
  var episodes = {};
  var notes = {};
  Object.keys(all).forEach(function (k) {
    if (k.indexOf('ep:') === 0 && all[k] && all[k].published !== false) episodes[k.slice(3)] = all[k];
    if (k.indexOf('notes:') === 0 && all[k] && all[k].published) notes[k.slice(6)] = all[k];
  });
  var league = Engine.publicLeague(all[LEAGUE_KEY]);
  // Show who has a winner bet / draft queue in (not what it is) so the lobby can nudge people.
  var byId = all[PRIVATE_KEY].byId;
  league.players.forEach(function (p) {
    var pr = byId[p.id] || {};
    p.hasWinnerBet = !!pr.winnerPick;
    p.queueSize = (pr.queue || []).length;
  });
  return JSON.stringify({ league: league, episodes: episodes, notes: notes });
}

// When the main draft completes, the winner bets lock and become public.
function onDraftProgress(all, kind) {
  var league = all[LEAGUE_KEY];
  if (kind === 'main' && league.draft.status === 'complete' && !league.winnerBets) {
    var bets = {};
    var byId = all[PRIVATE_KEY].byId;
    Engine.activePlayers(league).forEach(function (p) {
      if (byId[p.id] && byId[p.id].winnerPick) bets[p.id] = byId[p.id].winnerPick;
    });
    league.winnerBets = bets;
  }
}

// ---------- Players ----------
function normEmail(s) { return String(s || '').trim().toLowerCase(); }
function normName(s) { return String(s || '').replace(/\s+/g, ' ').trim(); }

function findByEmail(all, email) {
  email = normEmail(email);
  if (!email) return null;
  var byId = all[PRIVATE_KEY].byId;
  var league = all[LEAGUE_KEY];
  for (var i = 0; i < league.players.length; i++) {
    var p = league.players[i];
    if (!p.removed && byId[p.id] && byId[p.id].email === email) return p;
  }
  return null;
}

// Players are identified by their personal link token (preferred) or their email.
function findPlayer(all, b) {
  var tok = String(b.token || '');
  if (tok) {
    var byId = all[PRIVATE_KEY].byId;
    var league = all[LEAGUE_KEY];
    for (var i = 0; i < league.players.length; i++) {
      var p = league.players[i];
      if (!p.removed && byId[p.id] && byId[p.id].token === tok) return p;
    }
    if (!b.email) return null;
  }
  return findByEmail(all, b.email);
}

function newToken() {
  return (Math.random().toString(36).slice(2, 8) + Math.random().toString(36).slice(2, 8)).slice(0, 10);
}

function meView(all, p) {
  var pr = all[PRIVATE_KEY].byId[p.id] || {};
  return { id: p.id, name: p.name, color: p.color, email: pr.email, token: pr.token || null, queue: pr.queue || [], winnerPick: pr.winnerPick || null };
}

function validCastaway(id) {
  for (var i = 0; i < CAST.length; i++) if (CAST[i].id === id) return true;
  return false;
}

function cleanQueue(q) {
  if (!Array.isArray(q)) return [];
  var seen = {};
  return q.filter(function (id) {
    if (!validCastaway(id) || seen[id]) return false;
    seen[id] = true; return true;
  }).slice(0, 40);
}

function addPlayer(all, name, email, extra) {
  var league = all[LEAGUE_KEY];
  name = normName(name).slice(0, 40);
  email = normEmail(email);
  if (!name) Engine.fail('missing_name');
  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) Engine.fail('bad_email');
  if (findByEmail(all, email)) Engine.fail('email_taken');
  var taken = league.players.some(function (p) { return !p.removed && p.name.toLowerCase() === name.toLowerCase(); });
  if (taken) Engine.fail('name_taken');
  var used = {};
  Engine.activePlayers(league).forEach(function (p) { used[p.color] = true; });
  var color = Engine.PLAYER_COLORS.filter(function (c) { return !used[c]; })[0] || Engine.PLAYER_COLORS[league.players.length % Engine.PLAYER_COLORS.length];
  var id = 'p' + Math.random().toString(36).slice(2, 8);
  var p = { id: id, name: name, color: color, joinedAt: Date.now() };
  league.players.push(p);
  all[PRIVATE_KEY].byId[id] = {
    email: email,
    token: newToken(),
    queue: cleanQueue(extra && extra.queue),
    winnerPick: extra && validCastaway(extra.winnerPick) ? extra.winnerPick : null
  };
  return p;
}

function actJoin(b) {
  var all = loadAll();
  var existing = findByEmail(all, b.email);
  if (existing) return { me: meView(all, existing), existing: true };
  if (all[LEAGUE_KEY].draft.status !== 'open') Engine.fail('draft_started');
  var p = addPlayer(all, b.name, b.email, b);
  savePrivate(all);
  saveLeague(all, 'join:' + p.name);
  return { me: meView(all, p) };
}

function actLogin(b) {
  var all = loadAll();
  var p = findPlayer(all, b);
  if (!p) Engine.fail('not_found');
  return { me: meView(all, p) };
}

function actPrefs(b) {
  var all = loadAll();
  var p = findPlayer(all, b);
  if (!p) Engine.fail('not_found');
  var pr = all[PRIVATE_KEY].byId[p.id];
  if (b.queue !== undefined) pr.queue = cleanQueue(b.queue);
  if (b.winnerPick !== undefined) {
    if (all[LEAGUE_KEY].draft.status === 'complete' || all[LEAGUE_KEY].winnerBets) Engine.fail('winner_bet_locked');
    if (b.winnerPick !== null && !validCastaway(b.winnerPick)) Engine.fail('unknown_castaway');
    pr.winnerPick = b.winnerPick;
  }
  savePrivate(all);
  Platform.cacheClear();   // lobby shows who has a bet in
  return { me: meView(all, p) };
}

function actPick(b) {
  var all = loadAll();
  var league = all[LEAGUE_KEY];
  var kind = b.kind === 'merge' ? 'merge' : 'main';
  var p = findPlayer(all, b);
  if (!p) Engine.fail('not_found');
  var now = Date.now();
  // Run the clock first: if time ran out, the auto-pick lands and this submit is stale.
  var ticked = Engine.tick(league, CAST, kind, now - GRACE_MS, queuesOf(all));
  if (ticked) { onDraftProgress(all, kind); saveLeague(all, 'autopick'); }
  var slot = Engine.applyPick(league, CAST, kind, p.id, b.castawayId, { now: now, expectedN: b.n });
  onDraftProgress(all, kind);
  // Drop the picked castaway from everyone's queue position? No — queues are preferences;
  // auto-pick already skips anything illegal.
  saveLeague(all, 'pick:' + p.name + ':' + b.castawayId);
  return { slot: slot, league: Engine.publicLeague(league) };
}

// ---------- Admin ----------
function actAdmin(b) {
  var key = Platform.adminKey();
  if (!key || b.key !== key) Engine.fail('bad_admin_key');
  var all = loadAll();
  var league = all[LEAGUE_KEY];
  var now = Date.now();
  var kind = b.kind === 'merge' ? 'merge' : 'main';
  var draft = kind === 'merge' ? league.merge : league.draft;
  var out = {};

  switch (b.op) {
    case 'whoami':
      return { admin: true };

    case 'roster': {           // private player info for the admin console
      var byId = all[PRIVATE_KEY].byId;
      var minted = false;
      league.players.forEach(function (p) { if (byId[p.id] && !byId[p.id].token) { byId[p.id].token = newToken(); minted = true; } });
      if (minted) savePrivate(all);
      return { players: league.players.map(function (p) {
        var pr = byId[p.id] || {};
        return { id: p.id, name: p.name, color: p.color, removed: !!p.removed, email: pr.email, token: pr.token, queue: pr.queue || [], winnerPick: pr.winnerPick || null };
      }) };
    }

    case 'settings': {
      var allowed = ['rounds', 'maxPerCastaway', 'clockSec', 'scoringStartEp', 'mergeMaxPerCastaway', 'winnerBetPoints', 'lastEpisode'];
      allowed.forEach(function (k) {
        if (b.settings && b.settings[k] !== undefined) league.settings[k] = Number(b.settings[k]);
      });
      if (b.currentEp) league.currentEp = Number(b.currentEp);
      if (b.nextAir !== undefined) league.nextAir = b.nextAir;
      if (b.draftAt !== undefined) league.draftAt = b.draftAt;
      if (b.autoStart !== undefined) { league.autoStart = !!b.autoStart; league.autoStartError = null; }
      break;
    }

    case 'add_player': {
      var np = addPlayer(all, b.name, b.email, b);
      savePrivate(all);
      out.player = np;
      break;
    }

    case 'update_player': {
      var p = Engine.playerById(league, b.id);
      if (!p) Engine.fail('not_found');
      if (b.name) p.name = normName(b.name).slice(0, 40);
      if (b.color) p.color = b.color;
      if (b.removed !== undefined) {
        if (league.draft.status !== 'open' && b.removed) Engine.fail('draft_started');
        p.removed = !!b.removed;
      }
      if (b.email) { all[PRIVATE_KEY].byId[p.id].email = normEmail(b.email); savePrivate(all); }
      if (b.winnerPick !== undefined) { all[PRIVATE_KEY].byId[p.id].winnerPick = b.winnerPick; savePrivate(all); }
      break;
    }

    case 'start_draft':
      Engine.startDraft(league, CAST, { now: now, rounds: Number(b.rounds) || null, clockSec: Number(b.clockSec) || null, revealSec: Number(b.revealSec) || 0, order: b.order || null });
      break;

    case 'pause':  Engine.pause(draft, now); break;
    case 'resume': Engine.resume(draft, now); break;
    case 'undo':   out.undone = Engine.undo(draft, now);   // winner bets stay locked once revealed
      break;

    case 'pick_for': {
      var slot = Engine.currentSlot(draft);
      if (!slot) Engine.fail('draft_not_live');
      if (b.playerId && b.playerId !== slot.playerId) Engine.fail('stale_pick');
      Engine.applyPick(league, CAST, kind, slot.playerId, b.castawayId, { now: now, admin: true, auto: 'commissioner', expectedN: b.n });
      onDraftProgress(all, kind);
      break;
    }

    case 'autopick_now': {
      if (draft.status !== 'live') Engine.fail('draft_not_live');
      draft.deadline = now;
      Engine.tick(league, CAST, kind, now, queuesOf(all));
      onDraftProgress(all, kind);
      break;
    }

    case 'set_clock':
      draft.clockSec = Number(b.clockSec) || 0;
      if (draft.status === 'live') draft.deadline = draft.clockSec ? now + draft.clockSec * 1000 : null;
      break;

    case 'reset_draft':
      if (b.confirm !== 'RESET') Engine.fail('confirm_required');
      league.draft = Engine.newDraft('main');
      league.draft.rounds = league.settings.rounds;
      league.draft.clockSec = league.settings.clockSec;
      league.merge = Engine.newDraft('merge');
      league.winnerBets = null;
      break;

    case 'start_merge':
      if (!(Number(b.startEp) >= league.settings.scoringStartEp)) Engine.fail('bad_start_ep');
      Engine.startMerge(league, CAST, { now: now, order: b.order, startEp: Number(b.startEp), clockSec: Number(b.clockSec) || 0 });
      break;

    case 'save_episode': {
      var ep = Number(b.ep);
      if (!ep) Engine.fail('missing_ep');
      var data = b.data || {};
      var epObj = {
        ep: ep,
        title: String(data.title || '').slice(0, 120),
        airDate: data.airDate || null,
        scores: data.scores || {},
        eliminated: (data.eliminated || []).filter(function (x) { return validCastaway(x.id); }),
        published: data.published !== false,
        savedAt: now
      };
      Platform.storeSet('ep:' + ep, epObj);
      // Castaway status follows the episode: clear this episode's old eliminations, apply new ones.
      Object.keys(league.castaways).forEach(function (id) {
        if (league.castaways[id].eliminatedEp === ep && league.castaways[id].fromEpisode) delete league.castaways[id];
      });
      epObj.eliminated.forEach(function (x) {
        league.castaways[x.id] = { status: 'eliminated', eliminatedEp: ep, elimType: x.type || 'voted', fromEpisode: true };
      });
      if (ep > (league.currentEp || 0)) league.currentEp = ep;
      break;
    }

    case 'set_castaway': {
      if (!validCastaway(b.id)) Engine.fail('unknown_castaway');
      var o = league.castaways[b.id] || {};
      if (b.status) o.status = b.status;
      if (b.eliminatedEp !== undefined) o.eliminatedEp = b.eliminatedEp;
      if (b.elimType !== undefined) o.elimType = b.elimType;
      if (b.tribe) o.tribe = b.tribe;
      delete o.fromEpisode;
      league.castaways[b.id] = o;
      break;
    }

    case 'save_notes': {
      var n = Number(b.ep);
      if (!n && n !== 0) Engine.fail('missing_ep');
      Platform.storeSet('notes:' + n, {
        ep: n,
        title: String(b.title || '').slice(0, 160),
        body: String(b.body || '').slice(0, 45000),
        author: String(b.author || 'The Commissioner').slice(0, 60),
        published: b.published !== false,
        publishedAt: now
      });
      break;
    }

    case 'drafts': {           // everything incl. unpublished episodes and notes, admin only
      var notes = {}, eps = {};
      Object.keys(all).forEach(function (k) {
        if (k.indexOf('notes:') === 0) notes[k.slice(6)] = all[k];
        if (k.indexOf('ep:') === 0) eps[k.slice(3)] = all[k];
      });
      return { notes: notes, episodes: eps };
    }

    case 'backup':
      return { dump: loadAll() };

    default:
      Engine.fail('unknown_op');
  }

  saveLeague(all, 'admin:' + b.op);
  out.league = Engine.publicLeague(league);
  return out;
}
// =============================================================
// Google Apps Script platform layer: Sheet storage, cache, lock, admin key.
// dev/mock-server.js provides an in-memory replacement with the same shape.
//
// ONE-TIME SETUP (in the Apps Script editor):
//   1. Create a Google Sheet, then Extensions → Apps Script. Paste Code.gs.
//   2. Run `setup` once (authorizes, creates the Store sheet, prints the admin key).
//   3. Deploy → New deployment → Web app, Execute as: Me, Who has access: Anyone.
//   4. Paste the /exec URL into config.js (API_URL).
// =============================================================

var Platform = (function () {
  var STORE = 'Store';
  var BACKUPS = 'Backups';
  var CACHE_KEY = 'pub';
  var CHUNK = 30000;           // CacheService values max out at 100KB (bytes, and notes contain multi-byte characters)
  var _rows = null;            // per-execution index: key → row number

  function ss() { return SpreadsheetApp.getActiveSpreadsheet(); }

  function storeSheet() {
    var sh = ss().getSheetByName(STORE);
    if (!sh) {
      sh = ss().insertSheet(STORE);
      sh.getRange('A1:C1').setValues([['key', 'json', 'updated']]);
      sh.setFrozenRows(1);
    }
    return sh;
  }

  function storeLoadAll() {
    var sh = storeSheet();
    var vals = sh.getDataRange().getValues();
    var out = {};
    _rows = {};
    for (var i = 1; i < vals.length; i++) {
      var k = vals[i][0];
      if (!k) continue;
      _rows[k] = i + 1;
      try { out[k] = JSON.parse(vals[i][1]); } catch (e) { out[k] = null; }
    }
    return out;
  }

  function storeSet(key, value) {
    var sh = storeSheet();
    if (!_rows) storeLoadAll();
    var json = JSON.stringify(value);
    if (json.length > 49000) throw new Error('value_too_large:' + key);
    var row = _rows[key];
    if (!row) { row = sh.getLastRow() + 1; _rows[key] = row; }
    sh.getRange(row, 1, 1, 3).setValues([[key, json, new Date()]]);
  }

  function backup(reason, league) {
    try {
      var sh = ss().getSheetByName(BACKUPS) || ss().insertSheet(BACKUPS);
      var json = JSON.stringify(league);
      if (json.length < 49000) sh.appendRow([new Date(), reason, json]);
    } catch (e) { /* backups must never block a write */ }
  }

  function cachePut(body, meta) {
    try { cachePutUnsafe(body, meta); } catch (e) { /* a cache failure must never take the site down */ }
  }

  function cachePutUnsafe(body, meta) {
    var c = CacheService.getScriptCache();
    var parts = {};
    var n = Math.ceil(body.length / CHUNK) || 1;
    for (var i = 0; i < n; i++) parts[CACHE_KEY + ':' + i] = body.substr(i * CHUNK, CHUNK);
    parts[CACHE_KEY + ':meta'] = JSON.stringify({ n: n, meta: meta });
    c.putAll(parts, 300);
  }

  function cacheGet() {
    try { return cacheGetUnsafe(); } catch (e) { return null; }
  }

  function cacheGetUnsafe() {
    var c = CacheService.getScriptCache();
    var metaRaw = c.get(CACHE_KEY + ':meta');
    if (!metaRaw) return null;
    var m = JSON.parse(metaRaw);
    var keys = [];
    for (var i = 0; i < m.n; i++) keys.push(CACHE_KEY + ':' + i);
    var got = c.getAll(keys);
    var body = '';
    for (var j = 0; j < keys.length; j++) {
      if (got[keys[j]] == null) return null;
      body += got[keys[j]];
    }
    return { body: body, meta: m.meta || {} };
  }

  function cacheClear() {
    CacheService.getScriptCache().remove(CACHE_KEY + ':meta');
  }

  function withLock(fn) {
    var lock = LockService.getScriptLock();
    if (!lock.tryLock(10000)) { var e = new Error('server_busy'); e.code = 'server_busy'; throw e; }
    try { _rows = null; return fn(); } finally { lock.releaseLock(); }
  }

  function adminKey() {
    return PropertiesService.getScriptProperties().getProperty('ADMIN_KEY');
  }

  function json(obj) {
    return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);
  }

  function raw(str) {
    return ContentService.createTextOutput(str).setMimeType(ContentService.MimeType.JSON);
  }

  return {
    storeLoadAll: storeLoadAll, storeSet: storeSet, backup: backup,
    cachePut: cachePut, cacheGet: cacheGet, cacheClear: cacheClear,
    withLock: withLock, adminKey: adminKey, json: json, raw: raw
  };
})();

// Run once from the editor. Safe to re-run: keeps an existing admin key.
function setup() {
  var props = PropertiesService.getScriptProperties();
  var key = props.getProperty('ADMIN_KEY');
  if (!key) {
    key = Utilities.getUuid().replace(/-/g, '').slice(0, 20);
    props.setProperty('ADMIN_KEY', key);
  }
  Platform.withLock(function () {
    var all = Platform.storeLoadAll();
    if (!all.league) Platform.storeSet('league', Engine.newLeague(51));
    if (!all['private']) Platform.storeSet('private', { byId: {} });
  });
  console.log('Admin key: ' + key);
  return key;
}
