#!/bin/bash
# Builds the two generated files:
#   cast.js               ← cast.json (the site and the backend both load it)
#   apps-script/Code.gs   ← cast.js + engine.js + api.js + platform.js (paste into Apps Script)
set -euo pipefail
cd "$(dirname "$0")/.."

node -e '
const cast = require("./cast.json").map(c => ({
  id: c.id, name: c.name, shortName: c.shortName, age: c.age, hometown: c.hometown,
  occupation: c.occupation, tribe: c.tribe, startTribe: c.startTribe, status: c.status,
  eliminatedEp: c.eliminatedEp, photo: c.photo, fact: c.fact
}));
const out = "// GENERATED by tools/build.sh from cast.json — edit cast.json, not this file.\n" +
  "var CAST = " + JSON.stringify(cast, null, 1) + ";\n" +
  "var TRIBES = { Savu: { color: \"#8B4FC9\", buff: \"#5D2C78\" }, Toka: { color: \"#F5D422\", buff: \"#FEE137\" } };\n" +
  "var MACHINE = " + JSON.stringify(require("./machine.json"), null, 1) + ";\n" +
  "if (typeof module !== \"undefined\" && module.exports) module.exports = { CAST: CAST, TRIBES: TRIBES, MACHINE: MACHINE };\n";
require("fs").writeFileSync("cast.js", out);
'

{
  echo "// GENERATED by tools/build.sh — do not edit. Paste this whole file into the Apps Script editor."
  echo "// Built $(date '+%Y-%m-%d %H:%M')"
  cat cast.js engine.js apps-script/api.js apps-script/platform.js
} | grep -v '^if (typeof module' > apps-script/Code.gs

echo "built cast.js and apps-script/Code.gs ($(wc -l < apps-script/Code.gs) lines)"

# Cache-bust the site's own files so phones never run yesterday's JavaScript.
V=$(date +%s)
sed -i '' -E "s#(src|href)=\"(config|cast|engine|app)\.(js)(\?v=[0-9]+)?\"#\1=\"\2.\3?v=$V\"#g; s#href=\"styles\.css(\?v=[0-9]+)?\"#href=\"styles.css?v=$V\"#" index.html
echo "stamped index.html assets with v=$V"
